### ISSUE TITLE
Could you mind provide dataset that can be directly feed into  for model training?

### ISSUE THREAD

**Issue by weir12** [TencentAILabHealthcare/spatialID#4]
Hi:
First of all, thank you to your team for developing such an interesting and valuable model, and for the purpose of further understanding the article, I wanted to train the model mentioned in the article myself from scratch. 

As I understand it, you have detailed the various hyperparameters and training details of the model in the article, but there seems to be a gap between the raw single-cell data file and the data set used for feeding to iteration of the model.I think the following steps should be needed: gene filtration and cell filtration, normalization or logarithmization, and most importantly, how to annotate the types of cells)

However, relying solely on textual descriptions to preprocess and label data is prone to confusion and errors. I am not confident that my handling will fully reproduce your details :)

Is it possible to provide data set that can be used to reproduce the DNN model of the first stage and the Auto Encoder and classifier of the second stage?

Best wishes

Liang Ou

**Comment by SilversH** [comment]
Hi, you can find the unified dataset of H5AD format in our another work, SODB (Spatial Omics DataBase, https://gene.ai.tencent.com/SpatialOmics/)

**Comment by weir12** [comment]
Thanks!!!!!

**Comment by Smilenone** [comment]
> Hi, you can find the unified dataset of H5AD format in our another work, SODB (Spatial Omics DataBase, https://gene.ai.tencent.com/SpatialOmics/)

The website seems cannot be open
